"""End-to-end UI test against a real static HTTP server; no external map tile scraping."""
from pathlib import Path
import argparse,json,os
from playwright.sync_api import sync_playwright
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:4173');parser.add_argument('--output',default='test-results');args=parser.parse_args()
out=Path(args.output);out.mkdir(exist_ok=True,parents=True)
checks=[]
def check(name,value=True):
    assert value,name
    checks.append(name)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH'))
    context=browser.new_context(viewport={'width':1440,'height':1050},device_scale_factor=1,accept_downloads=True)
    # Do not trigger OSM raster tile loads from automated browsers. Local vector + NASA snapshot only.
    context.route('**/tile.openstreetmap.org/**',lambda route:route.abort())
    page=context.new_page();errors=[]
    page.on('pageerror',lambda e:(errors.append(str(e)),print('BROWSER_ERROR',str(e),getattr(e,'stack',''),flush=True)))
    page.goto(args.url,wait_until='networkidle');page.wait_for_selector('.research-switch');page.wait_for_timeout(200)
    page.locator('button[data-language="en"]').click()
    check('English mode translates research heading','Two research routes' in page.locator('h1').inner_text())
    check('Route 2 has a concrete research proposal in English','Cross-scale adaptive planning' in page.locator('.research-proposal').inner_text() and 'dry-season water constraint' in page.locator('.research-proposal').inner_text())
    check('Route 2 has falsifiable questions and source links',page.locator('.research-question-grid article').count()==3 and page.locator('.research-questions-foot a').count()==3)
    check('English mode sets document language',page.locator('html').get_attribute('lang')=='en')
    for name in ['research','overview','resources','analysis','planner','feedback','data','evidence','guide']:
        page.evaluate('(x)=>{location.hash=x}',name);page.wait_for_timeout(70)
        check(f'{name} default UI has no untranslated Chinese in English mode',not page.evaluate('''() => /[\u3400-\u9fff]/.test(document.querySelector('main').innerText)'''))
    page.evaluate('location.hash="research"');page.wait_for_timeout(70)
    page.locator('.top-version').click()
    check('English mode translates version dialog',not page.evaluate('''() => /[\u3400-\u9fff]/.test(document.querySelector('#modal').innerText)'''))
    page.locator('#modal [data-action="close-modal"]').first.click()
    page.locator('button[data-language="both"]').click()
    check('bilingual mode shows Chinese and English together','两条研究路线' in page.locator('h1').inner_text() and 'Two research routes' in page.locator('h1').inner_text())
    page.reload(wait_until='networkidle');page.wait_for_selector('.language-switch')
    check('language preference survives reload',page.locator('button[data-language="both"]').get_attribute('aria-pressed')=='true')
    page.locator('button[data-language="zh"]').click()
    check('Chinese mode restores source wording','两条研究路线' in page.locator('h1').inner_text() and 'Two research routes' not in page.locator('h1').inner_text())
    check('dual-route research home is default','海南全域' in page.locator('h1').all_inner_texts()[0] or '两条研究路线' in page.locator('h1').inner_text())
    check('provincial official snapshot is marked as province-only','412.37' in page.locator('.research-kpis').inner_text() and '海南省总体' in page.locator('.research-snapshot').inner_text())
    check('proposal includes all four platform scales',all(x in page.locator('.research-scales').inner_text() for x in ['农户','农场','村落','海南']))
    page.screenshot(path=str(out/'research-route2-desktop.png'),full_page=True)
    check('regional optimization remains gated','0/3 阶段就绪' in page.locator('.stage-heading').inner_text())
    with page.expect_download() as event:page.locator('[data-action="export-research-audit"]').click()
    event.value.save_as(str(out/'province-audit.csv'))
    check('provincial audit exports scale and source',(out/'province-audit.csv').read_text(encoding='utf-8-sig').find('county-series')>=0)
    page.locator('[data-research-track="farm"]').click()
    check('farm route is a separate scope','案例农场系统' in page.locator('.research-intro').inner_text() or '农户／农场' in page.locator('.research-intro').inner_text())
    page.locator('nav [data-nav="overview"]').click();page.wait_for_selector('.parcel')
    check('110 source prediction objects rendered',page.locator('.parcel').count()==110)
    check('no boot errors',not errors)
    page.screenshot(path=str(out/'overview-desktop.png'),full_page=True)
    check('visible version badge',page.locator('.top-version').inner_text()=='v0.3.4')
    page.locator('.top-version').click();check('independent model version in modal','screening-0.2.0' in page.locator('#modal').inner_text());page.screenshot(path=str(out/'version.png'));page.locator('[data-action="close-modal"]').first.click()
    page.locator('.parcel').first.dispatch_event('click');check('map updates inspector without replacing canvas',page.locator('.inspector').count()==1)
    page.locator('#show-osm').check();check('auxiliary source layer turns on',page.locator('.leaflet-source-pane path').count()==15)
    page.locator('#show-osm').uncheck();page.locator('#map-opacity').fill('25');page.locator('#map-opacity').dispatch_event('input');check('opacity control changes actual polygons',page.locator('.parcel').nth(1).get_attribute('fill-opacity')=='0.25')
    page.locator('[data-map="compare"]').click();check('image-only comparison hides geometry pane',page.locator('.leaflet-parcels-pane').evaluate('(e)=>e.style.opacity')=='0');page.locator('[data-map="compare"]').click()
    page.locator('nav [data-nav="evidence"]').click();check('quality checks are sourced','110' in page.locator('.selection-pipeline').inner_text());page.screenshot(path=str(out/'evidence.png'),full_page=True);page.locator('nav [data-nav="overview"]').click()

    def nav(name):page.locator(f'nav [data-nav="{name}"]').click()
    page.select_option('#scope','single');page.select_option('#scope-object','F01')
    check('single-actor scope changes selected object count','1 个主体 · 4 个空间单元' in page.locator('.scope-summary').inner_text())
    page.locator('[data-map="plus"]').click();page.locator('[data-map="fit"]').click()
    check('map zoom and fit',page.locator('.parcel').count()==110)
    page.locator('[data-basemap="satellite"]').click();page.wait_for_selector('.satellite-snapshot')
    page.wait_for_function("document.querySelector('.satellite-snapshot').complete && document.querySelector('.satellite-snapshot').naturalWidth > 0")
    check('georeferenced Sentinel-2 historical image loads',True)
    page.locator('[data-basemap="context"]').click()
    nav('resources');page.locator('[data-resource-tab="farms"]').click();page.locator('[data-action="edit-farm"]').first.click()
    page.locator('[name="water0"]').fill('19000');page.locator('#modal-form button[type="submit"]').click()
    saved=json.loads(page.evaluate("localStorage.getItem('farmsystem-workspace-v2')"))
    check('resource edit is actually persisted',next(f for f in saved['dataset']['farms'] if f['id']=='F01')['water'][0]==19000)
    nav('planner');page.locator('[data-action="run"]').first.click();page.wait_for_selector('[data-action="save-plan"]',timeout=45000)
    check('real module Worker returns candidates',page.locator('tr[data-candidate]').count()>0)
    page.screenshot(path=str(out/'planner-desktop.png'),full_page=True)
    page.locator('[data-action="save-plan"]').click();page.locator('[name="name"]').fill('测试方案 A');page.locator('#modal-form button[type="submit"]').click()
    page.locator('tr[data-candidate]').nth(1).click();page.locator('[data-action="save-plan"]').click();page.locator('[name="name"]').fill('测试方案 B');page.locator('#modal-form button[type="submit"]').click()
    page.locator('#water').fill('90');page.locator('#water').dispatch_event('input');page.locator('#water').dispatch_event('change')
    check('changed inputs make prior results explicitly stale',page.locator('[data-action="save-plan"]').is_disabled())
    nav('feedback');check('two saved snapshots',page.locator('[data-action="preview-plan"]').count()==2)
    page.locator('[data-action="intent-plan"]').first.click();check('adoption intention is not actual implementation','拟采用 · 非实施证明' in page.locator('body').inner_text())
    before=page.evaluate("JSON.parse(localStorage.getItem('farmsystem-workspace-v2')).dataset.plots.map(p=>p.crop).join('|')")
    page.locator('[data-action="preview-plan"]').first.click();check('plan has distinct preview layer','正在查看方案' in page.locator('body').inner_text())
    after=page.evaluate("JSON.parse(localStorage.getItem('farmsystem-workspace-v2')).dataset.plots.map(p=>p.crop).join('|')")
    check('scenario map does not overwrite baseline crops',before==after)
    nav('feedback');page.locator('[data-action="add-observation"]').click();page.locator('[name="value"]').fill('1000');page.locator('[name="date"]').fill('2025-03-31');page.locator('[name="note"]').fill('虚拟练习：与所选方案相同主体及2025年Q1全窗口口径。');page.locator('[name="sameScope"]').check();page.locator('#modal-form button[type="submit"]').click()
    check('feedback provenance and date recorded','虚拟练习' in page.locator('body').inner_text())
    nav('data')
    with page.expect_download() as event:page.locator('[data-action="export-weather"]').click()
    dl=event.value;dl.save_as(str(out/'weather.csv'))
    check('CSV export has actual twelve months',len((out/'weather.csv').read_text(encoding='utf-8-sig').splitlines())==13)
    with page.expect_download() as event:page.locator('[data-action="export-bundle"]').first.click()
    event.value.save_as(str(out/'project.json'));bundle=json.loads((out/'project.json').read_text(encoding='utf-8'))
    check('project export retains snapshots and observations',len(bundle['plans'])==2 and len(bundle['observations'])==1)
    check('export distinguishes app, model and regional evidence',bundle['version']=='0.3.4' and bundle['modelVersion']=='screening-0.2.0' and bundle['regionalEvidenceVersion']=='hainan-audit-2026-09-30-r2')
    page.locator('#import-file').set_input_files(str(out/'project.json'));page.wait_for_selector('#modal[open]');page.locator('#modal-form button[type="submit"]').click()
    check('project import round-trip',len(json.loads(page.evaluate("localStorage.getItem('farmsystem-workspace-v2')"))['plans'])==2)
    bad=out/'invalid.json';bad.write_text('{"schemaVersion":1,"crs":"GCJ-02"}')
    page.locator('#import-file').set_input_files(str(bad));page.wait_for_timeout(200)
    check('invalid CRS import rejected atomically','导入失败' in page.locator('#toast').inner_text())
    for name in ['research','overview','resources','analysis','planner','feedback','data','evidence','guide']:
        nav(name);check(f'{name} renders without fallback','当前输入无法计算' not in page.locator('h1').inner_text())
    nav('overview');page.reload(wait_until='networkidle');check('snapshots survive reload',len(json.loads(page.evaluate("localStorage.getItem('farmsystem-workspace-v2')"))['plans'])==2)
    page.wait_for_function('navigator.serviceWorker.controller !== null')
    context.set_offline(True);page.reload(wait_until='domcontentloaded');page.wait_for_selector('.parcel');page.wait_for_timeout(200)
    check('offline shell, vector snapshot and model modules load',page.locator('.parcel').count()==110)
    context.set_offline(False)
    page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(400);page.screenshot(path=str(out/'overview-mobile.png'),full_page=True)
    page.evaluate('location.hash="research"');page.wait_for_timeout(90);page.screenshot(path=str(out/'research-route2-mobile.png'),full_page=True)
    for name in ['research','overview','resources','analysis','planner','feedback','data','evidence','guide']:
        page.evaluate('(x)=>{location.hash=x}',name);page.wait_for_timeout(90)
        check(f'{name} mobile has no document overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
    page.locator('button[data-language="both"]').click()
    for name in ['research','overview','resources','analysis','planner','feedback','data','evidence','guide']:
        page.evaluate('(x)=>{location.hash=x}',name);page.wait_for_timeout(90)
        check(f'{name} bilingual mobile has no document overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
    (out/'browser-errors.json').write_text(json.dumps({'checks':checks,'errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')
    check('no JavaScript exceptions across workflow',not errors)
    browser.close()
(out/'browser-report.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'passed':len(checks),'checks':checks,'errors':errors},ensure_ascii=False))
