"""Deterministic source selection, not a claim of cadastral or field validation.
Re-run from this repository's unmodified public source snapshots. No invented geometry.
"""
from pathlib import Path
import json, hashlib, math
from collections import defaultdict
from shapely.geometry import shape, box, mapping
from shapely.ops import transform, unary_union
from pyproj import Geod, Transformer

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / 'data/evidence'
read = lambda n: json.loads((E/n).read_text())
write = lambda n,v: (E/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
ftw,osm,im = read('ftw-fields-2025.geojson'),read('agricultural-evidence.geojson'),read('sentinel-imagery.json')
g = Geod(ellps='WGS84'); proj = Transformer.from_crs(4326,32649,always_xy=True).transform
image_box = box(*im['bbox'])
patches = [(f,shape(f['geometry']),transform(proj,shape(f['geometry']))) for f in osm['features']]
union = unary_union([p[2] for p in patches])
selected=[]; exclusions=defaultdict(int); confidences=[]
for f in ftw['features']:
    p=shape(f['geometry']); props=f['properties']; confidences.append(props.get('confidence'))
    if p.geom_type!='Polygon' or not p.is_valid or p.is_empty:
        exclusions['invalid_or_non_polygon']+=1;continue
    a=abs(g.geometry_area_perimeter(p)[0])/10000
    if a<.1:
        exclusions['below_0_1_ha']+=1;continue
    if not image_box.covers(p):
        exclusions['not_fully_covered_by_image']+=1;continue
    pp=transform(proj,p); overlap=pp.intersection(union).area/pp.area
    if overlap<.9:
        exclusions['below_90pct_OSM_agricultural_overlap']+=1;continue
    parent=max(patches,key=lambda x: pp.intersection(x[2]).area)[0]
    selected.append((str(props['id']),f,p,a,overlap,str(parent['properties']['osmId'])))
selected.sort(key=lambda x:int(x[0]))
parents=sorted({x[-1] for x in selected},key=int)
parent_to_farm={v:f'F{i+1:02}' for i,v in enumerate(parents)}
# Hypothetical actors are placeholders; membership follows source patches for demonstration,
# NOT inferred ownership. Resource budgets below are explicit per-area teaching assumptions.
plots=[]
for i,(sid,f,p,a,overlap,parent) in enumerate(selected):
    point=list(p.representative_point().coords)[0]
    crop=['rice','vegetable','legume'][int(sid)%3]
    plots.append(dict(id=f'P{i+1:03}',name=f'预测单元 {i+1:03}',sourceId=sid,farmId=parent_to_farm[parent],geometry=f['geometry'],areaHa=round(a,7),representativePoint=list(point),crop=crop,locked=False,soilFactor=1,slopeDeg=None,soilN=None,actualCrop=None,actualOperator=None,provenance='synthetic',geometrySource='public-ml-prediction',sourceYear=2025,sourceUrl='https://source.coop/ftw/global-data',sourceConfidence=f['properties'].get('confidence'),confidenceMeaning='500m区域质量层；非地块正确概率；缺失不补造',parentOsmId=parent,osmOverlapFraction=round(overlap,8),geometrySha256=hashlib.sha256(json.dumps(f['geometry'],sort_keys=True,separators=(',',':')).encode()).hexdigest(),updatedAt='2026-09-30',note='原始公开遥感预测边界，未人工重画或分割；非确权地块。作物、主体归属和投入产出为假设，真实值未知。'))
farms=[]
for i,parent in enumerate(parents):
    fid=parent_to_farm[parent]; ps=[p for p in plots if p['farmId']==fid]; total=sum(p['areaHa'] for p in ps)
    unionp=unary_union([shape(p['geometry']) for p in ps]); point=list(unionp.representative_point().coords)[0]
    farms.append(dict(id=fid,name=f'假设主体 {i+1:02}',villageId=f'V{i%3+1:02}',kind='household',representative=i==0,provenance='synthetic',poultry=round(total*30) if i%3==0 else 0,water=[round(total*v,2) for v in [2500,2800,2300]],labour=[round(total*v,2) for v in [28,27,42]],center=list(point),sourcePatch=parent,note='仅按OSM用地斑块组织的假设决策主体，不对应真实经营者。供水2500/2800/2300 m³·ha⁻¹；用工28/27/42 工日·ha⁻¹，均为三个月演示配额。'))
villages=[]
for i in range(3):
    fs=[f for f in farms if f['villageId']==f'V{i+1:02}']; ps=[p for p in plots if p['farmId'] in {f['id'] for f in fs}]
    point=list(unary_union([shape(p['geometry']) for p in ps]).representative_point().coords)[0]
    villages.append(dict(id=f'V{i+1:02}',name=f'假设协作组 {chr(65+i)}',center=list(point),provenance='synthetic',note='非真实村界；资源共享仅为规划情景假设。'))
geom_union=unary_union([shape(p['geometry']) for p in plots]); extent=list(geom_union.bounds); center=list(geom_union.representative_point().coords)[0]
DATA_VERSION='evidence-2025-r1+assumptions-r2'
dataset=dict(schemaVersion=1,version=DATA_VERSION,crs='EPSG:4326',provenance='mixed',studyLabel='海南崖州附近 · 数据演示窗口，非已确认研究区',center=center,extent=extent,villages=villages,farms=farms,plots=plots,updatedAt='2026-09-30',notes='几何来自FTW 2025公开模型预测，使用完整源几何；以≥0.1ha、影像完整覆盖、OSM农业斑块重叠≥90%筛选。该筛选不是精度验证或代表性抽样。真实作物和经营者未知；生产与资源参数全部为演示假设。')
(ROOT/'src/evidence.generated.js').write_text('// Generated by tools/prepare_evidence.py; never manually redraw source geometry.\nexport const EVIDENCE_DATASET = '+json.dumps(dataset,ensure_ascii=False,separators=(',',':'))+';\n')
write('selected-fields.geojson',dict(type='FeatureCollection',metadata=dict(version=DATA_VERSION,selection=dataset['notes']),features=[dict(type='Feature',id=p['id'],geometry=p['geometry'],properties={k:v for k,v in p.items() if k!='geometry'}) for p in plots]))
# Pairwise checks in metric coordinates, no geometrical editing to force a pass.
pp=[transform(proj,shape(p['geometry'])) for p in plots]; overlaps=[]
for i,p in enumerate(pp):
    for j in range(i):
        q=pp[j]
        if p.intersects(q):
            a=p.intersection(q).area
            if a>.01: overlaps.append(dict(a=plots[j]['id'],b=plots[i]['id'],areaM2=round(a,5)))
checks=[dict(name='源几何逐坐标一致',passed=all(p['geometry']==f['geometry'] for p,(_,f,*_) in zip(plots,selected)),detail='保留原始顶点与孔洞，不进行平滑、切分或挪动'),dict(name='Polygon有效性与环闭合',passed=all(shape(p['geometry']).is_valid for p in plots),detail=f'{len(plots)} 个入选单元'),dict(name='相互重叠检查',passed=not overlaps,detail=f'容差0.01m²；{len(overlaps)} 对重叠'),dict(name='影像完整覆盖',passed=all(image_box.covers(shape(p['geometry'])) for p in plots),detail='入选几何完全位于本地Sentinel-2影像范围'),dict(name='关联完整性',passed=all(p['farmId'] in {f['id'] for f in farms} for p in plots),detail='每个单元关联一个明确标记的假设主体'),dict(name='面积口径',passed=True,detail='WGS84椭球面积，含孔洞；ha与亩通过1ha=15亩换算'),dict(name='未知属性保留缺失',passed=all(p['actualCrop'] is None and p['actualOperator'] is None and p['soilN'] is None for p in plots),detail='不从RGB编造作物、权属、土壤氮或NDVI'),dict(name='影像文件校验',passed=sha(E/'sentinel2-visual.webp')==im['sha256'],detail='SHA-256与获取元数据一致')]
report=dict(version=DATA_VERSION,builtOn='2026-09-30',sourcePredictionYear=2025,sourceCount=len(ftw['features']),osmPatchCount=len(patches),selectedCount=len(plots),actorCount=len(farms),selectedAreaHa=sum(p['areaHa'] for p in plots),exclusions=dict(exclusions),selection={'minAreaHa':.1,'minOSMOverlap':.90,'fullImageCoverage':True,'method':'All matching full Polygon features in downloaded spatial subset; no hand-picking or subdivision.','notValidation':True},checks=checks,overlapPairs=overlaps,confidenceMissing=sum(p['sourceConfidence'] is None for p in plots),licenses={'ftw':'CC-BY-4.0','osm':'ODbL-1.0','sentinel':'Contains modified Copernicus Sentinel data (2025)'},sourceHashes={n:sha(E/n) for n in ['ftw-fields-2025.geojson','agricultural-evidence.geojson','sentinel2-visual.webp','sentinel-imagery.json']},limitations=['无人地面核验的田界或地籍数据','OSM叠合只用于保守筛选，不是独立精度验证','研究区覆盖不完整，不能代表区域农业总量','单景2025历史RGB，不是实时状态或作物分类','归属、作物、价格、用水用工和禽类数均为假设'])
write('quality-report.json',report)
assert all(c['passed'] for c in checks), checks
print(json.dumps({k:report[k] for k in ['selectedCount','selectedAreaHa','actorCount','exclusions','confidenceMissing']},ensure_ascii=False,indent=2))
